version: "3.2"

services:

  tasks:
    command: bash
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    volumes:
      - .:/host
    extra_hosts:
      - "namenode:192.168.1.103"
      - "jobtracker:192.168.1.104"

