CLAMD_CONF = "/opt/heritrix/clamd/3310.conf"
HOOP_HOST="dls.httpfs.wa.bl.uk"
HOOP="http://" + HOOP_HOST + ":14000/webhdfs/v1"
HOOP_SUFFIX="?user.name=hadoop&op=OPEN"
HOOP_STATUS_SUFFIX="?user.name=hadoop&op=GETFILESTATUS"
