
'''
This contains the CLI tool for managing a file DB...
'''
import os
import csv
import sys
import json
import sqlite3
import logging
import argparse

logging.basicConfig(level=logging.WARNING, format='%(asctime)s: %(levelname)s - %(name)s - %(message)s')

logger = logging.getLogger(__name__)



def main():
    # Set up a parser:
    parser = argparse.ArgumentParser(prog='filedb')

    # Common arguments:
    parser.add_argument('-v', '--verbose',  action='count', default=0, help='Logging level; add more -v for more logging.')
    parser.add_argument('--dry-run', action='store_true', help='Do not modify the TrackDB.')
    parser.add_argument('-i', '--indent', type=int, help='Number of spaces to indent when emitting JSON.')

    # Use sub-parsers for different operations:
    subparsers = parser.add_subparsers(dest="op")
    subparsers.required = True

    # 'lsr-to-json' subcommand - read a file listing generated by hadoop fs -lsr ... and convert to JSON:
    parser_cv = subparsers.add_parser('lsr-to-jsonl', help='Read a hadoop fs -lsr format file listing and convert to JSONL')
    parser_cv.add_argument('input_lsr', type=str, help='The file to read, in hadoop fs -lsr format. Can be "-" for STDIN.')
    parser_cv.add_argument('output_jsonl', type=str, help='The file to output to in JSONL format. Can be "-" for STDOUT.')

    # 'lsr-to-sqllite' subcommand - read a file listing generated by hadoop fs -lsr ... and convert to SQLite:
    parser_sq = subparsers.add_parser('lsr-to-sqlite', help='Read a hadoop fs -lsr format file listing and convert to SQLite')
    parser_sq.add_argument('input_lsr', type=str, help='The file to read, in hadoop fs -lsr format. Can be "-" for STDIN.')
    parser_sq.add_argument('output_sqlite', type=str, help='The file to output to in SQLite format.')

    # And PARSE it:
    args = parser.parse_args()

    # Set up verbose logging:
    if args.verbose == 1:
        logging.getLogger().setLevel(logging.INFO)    
    elif args.verbose > 1:
        logging.getLogger().setLevel(logging.DEBUG)    

    # Set up client:
    st = WebHDFSStore(args.service, user_override=args.user)

    # Ops:
    logger.debug("Got args: %s" % args)
    if args.op == 'lsr-to-jsonl':
        # Input
        if args.input_lsr == '-':
            reader = sys.stdin
        else:
            reader = open(args.input_lsr, 'r')
        # Output
        if args.output_jsonl == '-':
            writer = sys.stdout
        else:
            writer = open(args.output_jsonl, 'w')

        # Convert and write out:
        counter = 0
        for item in st.lsr_to_items(reader):
            counter += 1
            writer.write(json.dumps(item))
            writer.write("\n")

        # Close up
        if reader is not sys.stdin.buffer:
            reader.close()
        if writer is not sys.stdout:
            writer.close()

        # Check this seems to have worked:
        if counter == 0:
            raise Exception("No records were found for conversion!")

    elif args.op == 'lsr-to-sqlite':
        # Input
        if args.input_lsr == '-':
            reader = sys.stdin
        else:
            reader = open(args.input_lsr, 'r')
        # Output
        con = sqlite3.connect(args.output_sqlite)
        cur = con.cursor()
        cur.execute('''CREATE TABLE IF NOT EXISTS files
               (id TEXT PRIMARY KEY ASC, collection TEXT, stream TEXT, kind TEXT, timestamp DATETIME, store TEXT, file_size INTEGER)''')

        # Convert and write out:
        counter = 0
        for item in st.lsr_to_items(reader):
            counter += 1
            cur.execute("INSERT OR IGNORE INTO files(id, collection, stream, kind, timestamp, store, file_size) \
                VALUES( '%(id)s', '%(collection_s)s', '%(stream_s)s', '%(kind_s)s',  '%(timestamp_dt)s',  '%(hdfs_service_id_s)s', %(file_size_l)s )" % item)

        # Close up
        if reader is not sys.stdin.buffer:
            reader.close()
        con.commit()
        con.close()

        # Check this seems to have worked:
        if counter == 0:
            raise Exception("No records were found for conversion!")

if __name__ == "__main__":
    main()
