hdfshost="194.66.232.90"
hdfsloguser="tomcat"
hdfslogroot="/logs"
logdirectories="/opt/tomcat/logs"
hdfscdxuser="rcoram"
hdfscdxroot="/user/rcoram/CDX_WITH_ARK"
localcdx="/wayback/cdx-index/index.cdx"
